apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fiducia-node
  namespace: fiducia
spec:
  template:
    spec:
      containers:
        - name: sidecar
          env:
            - name: FIDUCIA_NODE_ID
              value: fiducia-node-0.civo
