// @generated by quote-system/rust/scripts/model_codegen.py; do not edit by hand.

use bigdecimal::BigDecimal;
use chrono::{DateTime, Utc};
use diesel::prelude::*;
use serde_json::Value;

use crate::schema;

#[derive(Clone, Debug, PartialEq, Eq, Queryable, Selectable, Identifiable)]
#[diesel(table_name = schema::organizations)]
#[diesel(primary_key(tenant_id, organization_id))]
pub struct OrganizationRow {
    pub tenant_id: String,
    pub organization_id: String,
    pub legal_name_ciphertext: String,
    pub website_hostname: String,
    pub jurisdiction: String,
    pub entity_type: String,
    pub lifecycle_status: String,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

#[derive(Clone, Debug, PartialEq, Eq, Queryable, Selectable, Identifiable)]
#[diesel(table_name = schema::contacts)]
#[diesel(primary_key(tenant_id, contact_id))]
pub struct ContactRow {
    pub tenant_id: String,
    pub contact_id: String,
    pub full_name_ciphertext: String,
    pub work_email_ciphertext: String,
    pub work_email_lookup_hash: String,
    pub title_ciphertext: String,
    pub preferred_language: String,
    pub time_zone: String,
    pub lifecycle_status: String,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

#[derive(Clone, Debug, PartialEq, Eq, Queryable, Selectable, Identifiable)]
#[diesel(table_name = schema::organization_contact_roles)]
#[diesel(primary_key(tenant_id, organization_id, contact_id, role, valid_from))]
pub struct OrganizationContactRoleRow {
    pub tenant_id: String,
    pub organization_id: String,
    pub contact_id: String,
    pub role: String,
    pub valid_from: DateTime<Utc>,
    pub valid_until: Option<DateTime<Utc>>,
}

#[derive(Clone, Debug, PartialEq, Eq, Queryable, Selectable, Identifiable)]
#[diesel(table_name = schema::pre_interest_registrations)]
#[diesel(primary_key(tenant_id, submission_id))]
pub struct PreInterestRegistrationRow {
    pub tenant_id: String,
    pub submission_id: String,
    pub organization_id: String,
    pub requester_contact_id: String,
    pub status: String,
    pub schema_version: String,
    pub document_ciphertext: Value,
    pub document_sha256: String,
    pub consent_version: String,
    pub privacy_policy_version: String,
    pub email_verified_at: Option<DateTime<Utc>>,
    pub expires_at: DateTime<Utc>,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

#[derive(Clone, Debug, PartialEq, Eq, Queryable, Selectable, Identifiable)]
#[diesel(table_name = schema::applications)]
#[diesel(primary_key(tenant_id, application_id))]
pub struct ApplicationRow {
    pub tenant_id: String,
    pub application_id: String,
    pub organization_id: String,
    pub originating_submission_id: Option<String>,
    pub current_version: i32,
    pub current_status: String,
    pub current_etag: String,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

#[derive(Clone, Debug, PartialEq, Eq, Queryable, Selectable, Identifiable)]
#[diesel(table_name = schema::application_versions)]
#[diesel(primary_key(tenant_id, application_id, version))]
pub struct ApplicationVersionRow {
    pub tenant_id: String,
    pub application_id: String,
    pub version: i32,
    pub status: String,
    pub schema_version: String,
    pub document_ciphertext: Value,
    pub content_sha256: String,
    pub supersedes_version: Option<i32>,
    pub created_by_contact_id: Option<String>,
    pub created_by_subject_hash: String,
    pub created_at: DateTime<Utc>,
    pub submitted_at: Option<DateTime<Utc>>,
}

#[derive(Clone, Debug, PartialEq, Eq, Queryable, Selectable, Identifiable)]
#[diesel(table_name = schema::attachments)]
#[diesel(primary_key(tenant_id, attachment_id))]
pub struct AttachmentRow {
    pub tenant_id: String,
    pub attachment_id: String,
    pub application_id: String,
    pub application_version: i32,
    pub purpose: String,
    pub object_key_ciphertext: String,
    pub filename_ciphertext: String,
    pub media_type: String,
    pub size_bytes: i64,
    pub content_sha256: String,
    pub malware_scan_status: String,
    pub malware_scan_provider: Option<String>,
    pub malware_scan_completed_at: Option<DateTime<Utc>>,
    pub created_at: DateTime<Utc>,
}

#[derive(Clone, Debug, PartialEq, Eq, Queryable, Selectable, Identifiable)]
#[diesel(table_name = schema::support_plans)]
#[diesel(primary_key(tenant_id, support_plan_id))]
pub struct SupportPlanRow {
    pub tenant_id: String,
    pub support_plan_id: String,
    pub current_version: i32,
    pub current_status: String,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

#[derive(Clone, Debug, PartialEq, Eq, Queryable, Selectable, Identifiable)]
#[diesel(table_name = schema::support_plan_versions)]
#[diesel(primary_key(tenant_id, support_plan_id, version))]
pub struct SupportPlanVersionRow {
    pub tenant_id: String,
    pub support_plan_id: String,
    pub version: i32,
    pub status: String,
    pub name: String,
    pub tier: String,
    pub coverage: String,
    pub policy_document: Value,
    pub content_sha256: String,
    pub supersedes_version: Option<i32>,
    pub approved_by_subject_hash: Option<String>,
    pub approved_at: Option<DateTime<Utc>>,
    pub created_at: DateTime<Utc>,
}

#[derive(Clone, Debug, PartialEq, Eq, Queryable, Selectable, Identifiable)]
#[diesel(table_name = schema::sla_policies)]
#[diesel(primary_key(tenant_id, sla_policy_id))]
pub struct SlaPolicyRow {
    pub tenant_id: String,
    pub sla_policy_id: String,
    pub current_version: i32,
    pub current_status: String,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

#[derive(Clone, Debug, PartialEq, Eq, Queryable, Selectable, Identifiable)]
#[diesel(table_name = schema::sla_policy_versions)]
#[diesel(primary_key(tenant_id, sla_policy_id, version))]
pub struct SlaPolicyVersionRow {
    pub tenant_id: String,
    pub sla_policy_id: String,
    pub version: i32,
    pub status: String,
    pub name: String,
    pub availability_target_bps: i32,
    pub measurement_window: String,
    pub policy_document: Value,
    pub content_sha256: String,
    pub supersedes_version: Option<i32>,
    pub approved_by_subject_hash: Option<String>,
    pub approved_at: Option<DateTime<Utc>>,
    pub created_at: DateTime<Utc>,
}

#[derive(Clone, Debug, PartialEq, Eq, Queryable, Selectable, Identifiable)]
#[diesel(table_name = schema::contract_templates)]
#[diesel(primary_key(tenant_id, contract_template_id))]
pub struct ContractTemplateRow {
    pub tenant_id: String,
    pub contract_template_id: String,
    pub kind: String,
    pub current_version: i32,
    pub current_status: String,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

#[derive(Clone, Debug, PartialEq, Eq, Queryable, Selectable, Identifiable)]
#[diesel(table_name = schema::contract_template_versions)]
#[diesel(primary_key(tenant_id, contract_template_id, version))]
pub struct ContractTemplateVersionRow {
    pub tenant_id: String,
    pub contract_template_id: String,
    pub version: i32,
    pub status: String,
    pub document_object_key_ciphertext: String,
    pub content_sha256: String,
    pub supersedes_version: Option<i32>,
    pub approved_by_subject_hash: Option<String>,
    pub approved_at: Option<DateTime<Utc>>,
    pub created_at: DateTime<Utc>,
}

#[derive(Clone, Debug, PartialEq, Eq, Queryable, Selectable, Identifiable)]
#[diesel(table_name = schema::quotes)]
#[diesel(primary_key(tenant_id, quote_id))]
pub struct QuoteRow {
    pub tenant_id: String,
    pub quote_id: String,
    pub application_id: String,
    pub organization_id: String,
    pub current_version: i32,
    pub current_status: String,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

#[derive(Clone, Debug, PartialEq, Eq, Queryable, Selectable, Identifiable)]
#[diesel(table_name = schema::quote_versions)]
#[diesel(primary_key(tenant_id, quote_id, version))]
pub struct QuoteVersionRow {
    pub tenant_id: String,
    pub quote_id: String,
    pub version: i32,
    pub status: String,
    pub currency: String,
    pub term_months: i32,
    pub subtotal_minor_units: i64,
    pub discount_minor_units: i64,
    pub tax_minor_units: i64,
    pub total_minor_units: i64,
    pub minimum_commitment_minor_units: Option<i64>,
    pub support_plan_id: String,
    pub support_plan_version: i32,
    pub support_plan_sha256: String,
    pub sla_policy_id: String,
    pub sla_policy_version: i32,
    pub sla_policy_sha256: String,
    pub quote_document: Value,
    pub content_sha256: String,
    pub issued_at: Option<DateTime<Utc>>,
    pub valid_until: Option<DateTime<Utc>>,
    pub supersedes_version: Option<i32>,
    pub approved_by_subject_hash: Option<String>,
    pub approved_at: Option<DateTime<Utc>>,
    pub created_at: DateTime<Utc>,
}

#[derive(Clone, Debug, PartialEq, Eq, Queryable, Selectable, Identifiable)]
#[diesel(table_name = schema::quote_line_items)]
#[diesel(primary_key(tenant_id, quote_id, quote_version, line_item_id))]
pub struct QuoteLineItemRow {
    pub tenant_id: String,
    pub quote_id: String,
    pub quote_version: i32,
    pub line_item_id: String,
    pub display_order: i32,
    pub category: String,
    pub description: String,
    pub metric: String,
    pub quantity: BigDecimal,
    pub unit_price_minor_units: i64,
    pub extended_price_minor_units: i64,
    pub billing_frequency: String,
    pub pricing_metadata: Value,
}

#[derive(Clone, Debug, PartialEq, Eq, Queryable, Selectable, Identifiable)]
#[diesel(table_name = schema::quote_contract_references)]
#[diesel(primary_key(
    tenant_id,
    quote_id,
    quote_version,
    contract_template_id,
    contract_version
))]
pub struct QuoteContractReferenceRow {
    pub tenant_id: String,
    pub quote_id: String,
    pub quote_version: i32,
    pub contract_template_id: String,
    pub contract_version: i32,
    pub kind: String,
    pub content_sha256: String,
}

#[derive(Clone, Debug, PartialEq, Eq, Queryable, Selectable, Identifiable)]
#[diesel(table_name = schema::contract_acceptances)]
#[diesel(primary_key(tenant_id, acceptance_id))]
pub struct ContractAcceptanceRow {
    pub tenant_id: String,
    pub acceptance_id: String,
    pub organization_id: String,
    pub quote_id: String,
    pub quote_version: i32,
    pub quote_sha256: String,
    pub signer_contact_id: String,
    pub signer_authority_attested: bool,
    pub signature_provider: String,
    pub signature_evidence_id: String,
    pub signature_evidence_sha256: String,
    pub source_ip_hash: String,
    pub user_agent_hash: String,
    pub accepted_at: DateTime<Utc>,
    pub created_at: DateTime<Utc>,
}

#[derive(Clone, Debug, PartialEq, Eq, Queryable, Selectable, Identifiable)]
#[diesel(table_name = schema::workflow_transition_rules)]
#[diesel(primary_key(aggregate_type, from_state, to_state))]
pub struct WorkflowTransitionRuleRow {
    pub from_state: String,
    pub to_state: String,
    pub aggregate_type: String,
}

#[derive(Clone, Debug, PartialEq, Eq, Queryable, Selectable, Identifiable)]
#[diesel(table_name = schema::workflow_events)]
#[diesel(primary_key(tenant_id, event_id))]
pub struct WorkflowEventRow {
    pub tenant_id: String,
    pub event_id: String,
    pub aggregate_type: String,
    pub aggregate_id: String,
    pub sequence: i64,
    pub from_state: Option<String>,
    pub to_state: String,
    pub reason_code: String,
    pub actor_type: String,
    pub actor_subject_hash: String,
    pub request_id: String,
    pub idempotency_key_hash: String,
    pub before_version: Option<i32>,
    pub after_version: Option<i32>,
    pub source_ip_hash: Option<String>,
    pub session_hash: Option<String>,
    pub metadata: Value,
    pub occurred_at: DateTime<Utc>,
}

#[derive(Clone, Debug, PartialEq, Eq, Queryable, Selectable, Identifiable)]
#[diesel(table_name = schema::idempotency_records)]
#[diesel(primary_key(tenant_id, scope, idempotency_key_hash))]
pub struct IdempotencyRecordRow {
    pub tenant_id: String,
    pub scope: String,
    pub idempotency_key_hash: String,
    pub request_sha256: String,
    pub response_status: Option<i32>,
    pub response_sha256: Option<String>,
    pub resource_type: Option<String>,
    pub resource_id: Option<String>,
    pub state: String,
    pub created_at: DateTime<Utc>,
    pub completed_at: Option<DateTime<Utc>>,
    pub expires_at: DateTime<Utc>,
}

#[derive(Clone, Debug, PartialEq, Eq, Queryable, Selectable, Identifiable)]
#[diesel(table_name = schema::outbox_events)]
#[diesel(primary_key(tenant_id, outbox_event_id))]
pub struct OutboxEventRow {
    pub tenant_id: String,
    pub outbox_event_id: String,
    pub aggregate_type: String,
    pub aggregate_id: String,
    pub event_type: String,
    pub payload_ciphertext: Value,
    pub payload_sha256: String,
    pub attempt_count: i32,
    pub available_at: DateTime<Utc>,
    pub delivered_at: Option<DateTime<Utc>>,
    pub dead_lettered_at: Option<DateTime<Utc>>,
    pub last_error_code: Option<String>,
    pub created_at: DateTime<Utc>,
}
