// @generated by quote-system/rust/scripts/model_codegen.py; do not edit by hand.

diesel::table! {
    fiducia_commercial.organizations (tenant_id, organization_id) {
        tenant_id -> Text,
        organization_id -> Text,
        legal_name_ciphertext -> Text,
        website_hostname -> Text,
        jurisdiction -> Bpchar,
        entity_type -> Text,
        lifecycle_status -> Text,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    fiducia_commercial.contacts (tenant_id, contact_id) {
        tenant_id -> Text,
        contact_id -> Text,
        full_name_ciphertext -> Text,
        work_email_ciphertext -> Text,
        work_email_lookup_hash -> Text,
        title_ciphertext -> Text,
        preferred_language -> Text,
        time_zone -> Text,
        lifecycle_status -> Text,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    fiducia_commercial.organization_contact_roles (tenant_id, organization_id, contact_id, role, valid_from) {
        tenant_id -> Text,
        organization_id -> Text,
        contact_id -> Text,
        role -> Text,
        valid_from -> Timestamptz,
        valid_until -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    fiducia_commercial.pre_interest_registrations (tenant_id, submission_id) {
        tenant_id -> Text,
        submission_id -> Text,
        organization_id -> Text,
        requester_contact_id -> Text,
        status -> Text,
        schema_version -> Text,
        document_ciphertext -> Jsonb,
        document_sha256 -> Text,
        consent_version -> Text,
        privacy_policy_version -> Text,
        email_verified_at -> Nullable<Timestamptz>,
        expires_at -> Timestamptz,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    fiducia_commercial.applications (tenant_id, application_id) {
        tenant_id -> Text,
        application_id -> Text,
        organization_id -> Text,
        originating_submission_id -> Nullable<Text>,
        current_version -> Int4,
        current_status -> Text,
        current_etag -> Text,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    fiducia_commercial.application_versions (tenant_id, application_id, version) {
        tenant_id -> Text,
        application_id -> Text,
        version -> Int4,
        status -> Text,
        schema_version -> Text,
        document_ciphertext -> Jsonb,
        content_sha256 -> Text,
        supersedes_version -> Nullable<Int4>,
        created_by_contact_id -> Nullable<Text>,
        created_by_subject_hash -> Text,
        created_at -> Timestamptz,
        submitted_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    fiducia_commercial.attachments (tenant_id, attachment_id) {
        tenant_id -> Text,
        attachment_id -> Text,
        application_id -> Text,
        application_version -> Int4,
        purpose -> Text,
        object_key_ciphertext -> Text,
        filename_ciphertext -> Text,
        media_type -> Text,
        size_bytes -> Int8,
        content_sha256 -> Text,
        malware_scan_status -> Text,
        malware_scan_provider -> Nullable<Text>,
        malware_scan_completed_at -> Nullable<Timestamptz>,
        created_at -> Timestamptz,
    }
}

diesel::table! {
    fiducia_commercial.support_plans (tenant_id, support_plan_id) {
        tenant_id -> Text,
        support_plan_id -> Text,
        current_version -> Int4,
        current_status -> Text,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    fiducia_commercial.support_plan_versions (tenant_id, support_plan_id, version) {
        tenant_id -> Text,
        support_plan_id -> Text,
        version -> Int4,
        status -> Text,
        name -> Text,
        tier -> Text,
        coverage -> Text,
        policy_document -> Jsonb,
        content_sha256 -> Text,
        supersedes_version -> Nullable<Int4>,
        approved_by_subject_hash -> Nullable<Text>,
        approved_at -> Nullable<Timestamptz>,
        created_at -> Timestamptz,
    }
}

diesel::table! {
    fiducia_commercial.sla_policies (tenant_id, sla_policy_id) {
        tenant_id -> Text,
        sla_policy_id -> Text,
        current_version -> Int4,
        current_status -> Text,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    fiducia_commercial.sla_policy_versions (tenant_id, sla_policy_id, version) {
        tenant_id -> Text,
        sla_policy_id -> Text,
        version -> Int4,
        status -> Text,
        name -> Text,
        availability_target_bps -> Int4,
        measurement_window -> Text,
        policy_document -> Jsonb,
        content_sha256 -> Text,
        supersedes_version -> Nullable<Int4>,
        approved_by_subject_hash -> Nullable<Text>,
        approved_at -> Nullable<Timestamptz>,
        created_at -> Timestamptz,
    }
}

diesel::table! {
    fiducia_commercial.contract_templates (tenant_id, contract_template_id) {
        tenant_id -> Text,
        contract_template_id -> Text,
        kind -> Text,
        current_version -> Int4,
        current_status -> Text,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    fiducia_commercial.contract_template_versions (tenant_id, contract_template_id, version) {
        tenant_id -> Text,
        contract_template_id -> Text,
        version -> Int4,
        status -> Text,
        document_object_key_ciphertext -> Text,
        content_sha256 -> Text,
        supersedes_version -> Nullable<Int4>,
        approved_by_subject_hash -> Nullable<Text>,
        approved_at -> Nullable<Timestamptz>,
        created_at -> Timestamptz,
    }
}

diesel::table! {
    fiducia_commercial.quotes (tenant_id, quote_id) {
        tenant_id -> Text,
        quote_id -> Text,
        application_id -> Text,
        organization_id -> Text,
        current_version -> Int4,
        current_status -> Text,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    fiducia_commercial.quote_versions (tenant_id, quote_id, version) {
        tenant_id -> Text,
        quote_id -> Text,
        version -> Int4,
        status -> Text,
        currency -> Bpchar,
        term_months -> Int4,
        subtotal_minor_units -> Int8,
        discount_minor_units -> Int8,
        tax_minor_units -> Int8,
        total_minor_units -> Int8,
        minimum_commitment_minor_units -> Nullable<Int8>,
        support_plan_id -> Text,
        support_plan_version -> Int4,
        support_plan_sha256 -> Text,
        sla_policy_id -> Text,
        sla_policy_version -> Int4,
        sla_policy_sha256 -> Text,
        quote_document -> Jsonb,
        content_sha256 -> Text,
        issued_at -> Nullable<Timestamptz>,
        valid_until -> Nullable<Timestamptz>,
        supersedes_version -> Nullable<Int4>,
        approved_by_subject_hash -> Nullable<Text>,
        approved_at -> Nullable<Timestamptz>,
        created_at -> Timestamptz,
    }
}

diesel::table! {
    fiducia_commercial.quote_line_items (tenant_id, quote_id, quote_version, line_item_id) {
        tenant_id -> Text,
        quote_id -> Text,
        quote_version -> Int4,
        line_item_id -> Text,
        display_order -> Int4,
        category -> Text,
        description -> Text,
        metric -> Text,
        quantity -> Numeric,
        unit_price_minor_units -> Int8,
        extended_price_minor_units -> Int8,
        billing_frequency -> Text,
        pricing_metadata -> Jsonb,
    }
}

diesel::table! {
    fiducia_commercial.quote_contract_references (tenant_id, quote_id, quote_version, contract_template_id, contract_version) {
        tenant_id -> Text,
        quote_id -> Text,
        quote_version -> Int4,
        contract_template_id -> Text,
        contract_version -> Int4,
        kind -> Text,
        content_sha256 -> Text,
    }
}

diesel::table! {
    fiducia_commercial.contract_acceptances (tenant_id, acceptance_id) {
        tenant_id -> Text,
        acceptance_id -> Text,
        organization_id -> Text,
        quote_id -> Text,
        quote_version -> Int4,
        quote_sha256 -> Text,
        signer_contact_id -> Text,
        signer_authority_attested -> Bool,
        signature_provider -> Text,
        signature_evidence_id -> Text,
        signature_evidence_sha256 -> Text,
        source_ip_hash -> Text,
        user_agent_hash -> Text,
        accepted_at -> Timestamptz,
        created_at -> Timestamptz,
    }
}

diesel::table! {
    fiducia_commercial.workflow_transition_rules (aggregate_type, from_state, to_state) {
        from_state -> Text,
        to_state -> Text,
        aggregate_type -> Text,
    }
}

diesel::table! {
    fiducia_commercial.workflow_events (tenant_id, event_id) {
        tenant_id -> Text,
        event_id -> Text,
        aggregate_type -> Text,
        aggregate_id -> Text,
        sequence -> Int8,
        from_state -> Nullable<Text>,
        to_state -> Text,
        reason_code -> Text,
        actor_type -> Text,
        actor_subject_hash -> Text,
        request_id -> Text,
        idempotency_key_hash -> Text,
        before_version -> Nullable<Int4>,
        after_version -> Nullable<Int4>,
        source_ip_hash -> Nullable<Text>,
        session_hash -> Nullable<Text>,
        metadata -> Jsonb,
        occurred_at -> Timestamptz,
    }
}

diesel::table! {
    fiducia_commercial.idempotency_records (tenant_id, scope, idempotency_key_hash) {
        tenant_id -> Text,
        scope -> Text,
        idempotency_key_hash -> Text,
        request_sha256 -> Text,
        response_status -> Nullable<Int4>,
        response_sha256 -> Nullable<Text>,
        resource_type -> Nullable<Text>,
        resource_id -> Nullable<Text>,
        state -> Text,
        created_at -> Timestamptz,
        completed_at -> Nullable<Timestamptz>,
        expires_at -> Timestamptz,
    }
}

diesel::table! {
    fiducia_commercial.outbox_events (tenant_id, outbox_event_id) {
        tenant_id -> Text,
        outbox_event_id -> Text,
        aggregate_type -> Text,
        aggregate_id -> Text,
        event_type -> Text,
        payload_ciphertext -> Jsonb,
        payload_sha256 -> Text,
        attempt_count -> Int4,
        available_at -> Timestamptz,
        delivered_at -> Nullable<Timestamptz>,
        dead_lettered_at -> Nullable<Timestamptz>,
        last_error_code -> Nullable<Text>,
        created_at -> Timestamptz,
    }
}

