// @generated by quote-system/rust/scripts/model_codegen.py; do not edit by hand.
#![allow(clippy::module_name_repetitions)]

// SeaORM entities projected from `db/0001_commercial_intake.sql`.
//
// Public API payloads remain owned by TypeSpec and JSON Schema. These models
// intentionally represent encrypted persistence rows only.

pub mod contract_template_versions {
    use sea_orm::entity::prelude::*;

    #[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
    #[sea_orm(
        table_name = "contract_template_versions",
        schema_name = "fiducia_commercial"
    )]
    pub struct Model {
        #[sea_orm(primary_key, auto_increment = false)]
        pub tenant_id: String,
        #[sea_orm(primary_key, auto_increment = false)]
        pub contract_template_id: String,
        #[sea_orm(primary_key, auto_increment = false)]
        pub version: i32,
        pub status: String,
        pub document_object_key_ciphertext: String,
        pub content_sha256: String,
        pub supersedes_version: Option<i32>,
        pub approved_by_subject_hash: Option<String>,
        pub approved_at: Option<DateTimeWithTimeZone>,
        pub created_at: DateTimeWithTimeZone,
    }

    #[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
    pub enum Relation {}

    impl ActiveModelBehavior for ActiveModel {}
}

pub mod quotes {
    use sea_orm::entity::prelude::*;

    #[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
    #[sea_orm(table_name = "quotes", schema_name = "fiducia_commercial")]
    pub struct Model {
        #[sea_orm(primary_key, auto_increment = false)]
        pub tenant_id: String,
        #[sea_orm(primary_key, auto_increment = false)]
        pub quote_id: String,
        pub application_id: String,
        pub organization_id: String,
        pub current_version: i32,
        pub current_status: String,
        pub created_at: DateTimeWithTimeZone,
        pub updated_at: DateTimeWithTimeZone,
    }

    #[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
    pub enum Relation {}

    impl ActiveModelBehavior for ActiveModel {}
}

pub mod quote_versions {
    use sea_orm::entity::prelude::*;

    #[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
    #[sea_orm(table_name = "quote_versions", schema_name = "fiducia_commercial")]
    pub struct Model {
        #[sea_orm(primary_key, auto_increment = false)]
        pub tenant_id: String,
        #[sea_orm(primary_key, auto_increment = false)]
        pub quote_id: String,
        #[sea_orm(primary_key, auto_increment = false)]
        pub version: i32,
        pub status: String,
        pub currency: String,
        pub term_months: i32,
        pub subtotal_minor_units: i64,
        pub discount_minor_units: i64,
        pub tax_minor_units: i64,
        pub total_minor_units: i64,
        pub minimum_commitment_minor_units: Option<i64>,
        pub support_plan_id: String,
        pub support_plan_version: i32,
        pub support_plan_sha256: String,
        pub sla_policy_id: String,
        pub sla_policy_version: i32,
        pub sla_policy_sha256: String,
        pub quote_document: Json,
        pub content_sha256: String,
        pub issued_at: Option<DateTimeWithTimeZone>,
        pub valid_until: Option<DateTimeWithTimeZone>,
        pub supersedes_version: Option<i32>,
        pub approved_by_subject_hash: Option<String>,
        pub approved_at: Option<DateTimeWithTimeZone>,
        pub created_at: DateTimeWithTimeZone,
    }

    #[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
    pub enum Relation {}

    impl ActiveModelBehavior for ActiveModel {}
}

pub mod quote_line_items {
    use sea_orm::entity::prelude::*;

    #[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
    #[sea_orm(table_name = "quote_line_items", schema_name = "fiducia_commercial")]
    pub struct Model {
        #[sea_orm(primary_key, auto_increment = false)]
        pub tenant_id: String,
        #[sea_orm(primary_key, auto_increment = false)]
        pub quote_id: String,
        #[sea_orm(primary_key, auto_increment = false)]
        pub quote_version: i32,
        #[sea_orm(primary_key, auto_increment = false)]
        pub line_item_id: String,
        pub display_order: i32,
        pub category: String,
        pub description: String,
        pub metric: String,
        pub quantity: Decimal,
        pub unit_price_minor_units: i64,
        pub extended_price_minor_units: i64,
        pub billing_frequency: String,
        pub pricing_metadata: Json,
    }

    #[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
    pub enum Relation {}

    impl ActiveModelBehavior for ActiveModel {}
}

pub mod quote_contract_references {
    use sea_orm::entity::prelude::*;

    #[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
    #[sea_orm(
        table_name = "quote_contract_references",
        schema_name = "fiducia_commercial"
    )]
    pub struct Model {
        #[sea_orm(primary_key, auto_increment = false)]
        pub tenant_id: String,
        #[sea_orm(primary_key, auto_increment = false)]
        pub quote_id: String,
        #[sea_orm(primary_key, auto_increment = false)]
        pub quote_version: i32,
        #[sea_orm(primary_key, auto_increment = false)]
        pub contract_template_id: String,
        #[sea_orm(primary_key, auto_increment = false)]
        pub contract_version: i32,
        pub kind: String,
        pub content_sha256: String,
    }

    #[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
    pub enum Relation {}

    impl ActiveModelBehavior for ActiveModel {}
}
