// @generated by quote-system/rust/scripts/model_codegen.py; do not edit by hand.
#![allow(clippy::module_name_repetitions)]

/// SeaORM entities projected from `db/0001_commercial_intake.sql`.
///
/// Public API payloads remain owned by TypeSpec and JSON Schema. These models
/// intentionally represent encrypted persistence rows only.

pub mod organizations {
    use sea_orm::entity::prelude::*;

    #[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
    #[sea_orm(table_name = "organizations", schema_name = "fiducia_commercial")]
    pub struct Model {
        #[sea_orm(primary_key, auto_increment = false)]
        pub tenant_id: String,
        #[sea_orm(primary_key, auto_increment = false)]
        pub organization_id: String,
        pub legal_name_ciphertext: String,
        pub website_hostname: String,
        pub jurisdiction: String,
        pub entity_type: String,
        pub lifecycle_status: String,
        pub created_at: DateTimeWithTimeZone,
        pub updated_at: DateTimeWithTimeZone,
    }

    #[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
    pub enum Relation {}

    impl ActiveModelBehavior for ActiveModel {}
}

pub mod contacts {
    use sea_orm::entity::prelude::*;

    #[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
    #[sea_orm(table_name = "contacts", schema_name = "fiducia_commercial")]
    pub struct Model {
        #[sea_orm(primary_key, auto_increment = false)]
        pub tenant_id: String,
        #[sea_orm(primary_key, auto_increment = false)]
        pub contact_id: String,
        pub full_name_ciphertext: String,
        pub work_email_ciphertext: String,
        pub work_email_lookup_hash: String,
        pub title_ciphertext: String,
        pub preferred_language: String,
        pub time_zone: String,
        pub lifecycle_status: String,
        pub created_at: DateTimeWithTimeZone,
        pub updated_at: DateTimeWithTimeZone,
    }

    #[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
    pub enum Relation {}

    impl ActiveModelBehavior for ActiveModel {}
}

pub mod organization_contact_roles {
    use sea_orm::entity::prelude::*;

    #[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
    #[sea_orm(
        table_name = "organization_contact_roles",
        schema_name = "fiducia_commercial"
    )]
    pub struct Model {
        #[sea_orm(primary_key, auto_increment = false)]
        pub tenant_id: String,
        #[sea_orm(primary_key, auto_increment = false)]
        pub organization_id: String,
        #[sea_orm(primary_key, auto_increment = false)]
        pub contact_id: String,
        #[sea_orm(primary_key, auto_increment = false)]
        pub role: String,
        #[sea_orm(primary_key, auto_increment = false)]
        pub valid_from: DateTimeWithTimeZone,
        pub valid_until: Option<DateTimeWithTimeZone>,
    }

    #[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
    pub enum Relation {}

    impl ActiveModelBehavior for ActiveModel {}
}

pub mod pre_interest_registrations {
    use sea_orm::entity::prelude::*;

    #[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
    #[sea_orm(
        table_name = "pre_interest_registrations",
        schema_name = "fiducia_commercial"
    )]
    pub struct Model {
        #[sea_orm(primary_key, auto_increment = false)]
        pub tenant_id: String,
        #[sea_orm(primary_key, auto_increment = false)]
        pub submission_id: String,
        pub organization_id: String,
        pub requester_contact_id: String,
        pub status: String,
        pub schema_version: String,
        pub document_ciphertext: Json,
        pub document_sha256: String,
        pub consent_version: String,
        pub privacy_policy_version: String,
        pub email_verified_at: Option<DateTimeWithTimeZone>,
        pub expires_at: DateTimeWithTimeZone,
        pub created_at: DateTimeWithTimeZone,
        pub updated_at: DateTimeWithTimeZone,
    }

    #[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
    pub enum Relation {}

    impl ActiveModelBehavior for ActiveModel {}
}

pub mod applications {
    use sea_orm::entity::prelude::*;

    #[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
    #[sea_orm(table_name = "applications", schema_name = "fiducia_commercial")]
    pub struct Model {
        #[sea_orm(primary_key, auto_increment = false)]
        pub tenant_id: String,
        #[sea_orm(primary_key, auto_increment = false)]
        pub application_id: String,
        pub organization_id: String,
        pub originating_submission_id: Option<String>,
        pub current_version: i32,
        pub current_status: String,
        pub current_etag: String,
        pub created_at: DateTimeWithTimeZone,
        pub updated_at: DateTimeWithTimeZone,
    }

    #[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
    pub enum Relation {}

    impl ActiveModelBehavior for ActiveModel {}
}

pub mod application_versions {
    use sea_orm::entity::prelude::*;

    #[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
    #[sea_orm(
        table_name = "application_versions",
        schema_name = "fiducia_commercial"
    )]
    pub struct Model {
        #[sea_orm(primary_key, auto_increment = false)]
        pub tenant_id: String,
        #[sea_orm(primary_key, auto_increment = false)]
        pub application_id: String,
        #[sea_orm(primary_key, auto_increment = false)]
        pub version: i32,
        pub status: String,
        pub schema_version: String,
        pub document_ciphertext: Json,
        pub content_sha256: String,
        pub supersedes_version: Option<i32>,
        pub created_by_contact_id: Option<String>,
        pub created_by_subject_hash: String,
        pub created_at: DateTimeWithTimeZone,
        pub submitted_at: Option<DateTimeWithTimeZone>,
    }

    #[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
    pub enum Relation {}

    impl ActiveModelBehavior for ActiveModel {}
}
