// @generated by quote-system/rust/scripts/model_codegen.py; do not edit by hand.
#![allow(clippy::module_name_repetitions)]

/// SeaORM entities projected from `db/0001_commercial_intake.sql`.
///
/// Public API payloads remain owned by TypeSpec and JSON Schema. These models
/// intentionally represent encrypted persistence rows only.

pub mod contract_acceptances {
    use sea_orm::entity::prelude::*;

    #[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
    #[sea_orm(table_name = "contract_acceptances", schema_name = "fiducia_commercial")]
    pub struct Model {
        #[sea_orm(primary_key, auto_increment = false)]
        pub tenant_id: String,
        #[sea_orm(primary_key, auto_increment = false)]
        pub acceptance_id: String,
        pub organization_id: String,
        pub quote_id: String,
        pub quote_version: i32,
        pub quote_sha256: String,
        pub signer_contact_id: String,
        pub signer_authority_attested: bool,
        pub signature_provider: String,
        pub signature_evidence_id: String,
        pub signature_evidence_sha256: String,
        pub source_ip_hash: String,
        pub user_agent_hash: String,
        pub accepted_at: DateTimeWithTimeZone,
        pub created_at: DateTimeWithTimeZone,
    }

    #[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
    pub enum Relation {}

    impl ActiveModelBehavior for ActiveModel {}
}

pub mod workflow_transition_rules {
    use sea_orm::entity::prelude::*;

    #[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
    #[sea_orm(table_name = "workflow_transition_rules", schema_name = "fiducia_commercial")]
    pub struct Model {
        #[sea_orm(primary_key, auto_increment = false)]
        pub from_state: String,
        #[sea_orm(primary_key, auto_increment = false)]
        pub to_state: String,
        #[sea_orm(primary_key, auto_increment = false)]
        pub aggregate_type: String,
    }

    #[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
    pub enum Relation {}

    impl ActiveModelBehavior for ActiveModel {}
}

pub mod workflow_events {
    use sea_orm::entity::prelude::*;

    #[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
    #[sea_orm(table_name = "workflow_events", schema_name = "fiducia_commercial")]
    pub struct Model {
        #[sea_orm(primary_key, auto_increment = false)]
        pub tenant_id: String,
        #[sea_orm(primary_key, auto_increment = false)]
        pub event_id: String,
        pub aggregate_type: String,
        pub aggregate_id: String,
        pub sequence: i64,
        pub from_state: Option<String>,
        pub to_state: String,
        pub reason_code: String,
        pub actor_type: String,
        pub actor_subject_hash: String,
        pub request_id: String,
        pub idempotency_key_hash: String,
        pub before_version: Option<i32>,
        pub after_version: Option<i32>,
        pub source_ip_hash: Option<String>,
        pub session_hash: Option<String>,
        pub metadata: Json,
        pub occurred_at: DateTimeWithTimeZone,
    }

    #[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
    pub enum Relation {}

    impl ActiveModelBehavior for ActiveModel {}
}

pub mod idempotency_records {
    use sea_orm::entity::prelude::*;

    #[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
    #[sea_orm(table_name = "idempotency_records", schema_name = "fiducia_commercial")]
    pub struct Model {
        #[sea_orm(primary_key, auto_increment = false)]
        pub tenant_id: String,
        #[sea_orm(primary_key, auto_increment = false)]
        pub scope: String,
        #[sea_orm(primary_key, auto_increment = false)]
        pub idempotency_key_hash: String,
        pub request_sha256: String,
        pub response_status: Option<i32>,
        pub response_sha256: Option<String>,
        pub resource_type: Option<String>,
        pub resource_id: Option<String>,
        pub state: String,
        pub created_at: DateTimeWithTimeZone,
        pub completed_at: Option<DateTimeWithTimeZone>,
        pub expires_at: DateTimeWithTimeZone,
    }

    #[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
    pub enum Relation {}

    impl ActiveModelBehavior for ActiveModel {}
}

pub mod outbox_events {
    use sea_orm::entity::prelude::*;

    #[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
    #[sea_orm(table_name = "outbox_events", schema_name = "fiducia_commercial")]
    pub struct Model {
        #[sea_orm(primary_key, auto_increment = false)]
        pub tenant_id: String,
        #[sea_orm(primary_key, auto_increment = false)]
        pub outbox_event_id: String,
        pub aggregate_type: String,
        pub aggregate_id: String,
        pub event_type: String,
        pub payload_ciphertext: Json,
        pub payload_sha256: String,
        pub attempt_count: i32,
        pub available_at: DateTimeWithTimeZone,
        pub delivered_at: Option<DateTimeWithTimeZone>,
        pub dead_lettered_at: Option<DateTimeWithTimeZone>,
        pub last_error_code: Option<String>,
        pub created_at: DateTimeWithTimeZone,
    }

    #[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
    pub enum Relation {}

    impl ActiveModelBehavior for ActiveModel {}
}
