// @generated by quote-system/rust/scripts/model_codegen.py; do not edit by hand.
#![allow(clippy::module_name_repetitions)]

/// SeaORM entities projected from `db/0001_commercial_intake.sql`.
///
/// Public API payloads remain owned by TypeSpec and JSON Schema. These models
/// intentionally represent encrypted persistence rows only.

pub mod attachments {
    use sea_orm::entity::prelude::*;

    #[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
    #[sea_orm(table_name = "attachments", schema_name = "fiducia_commercial")]
    pub struct Model {
        #[sea_orm(primary_key, auto_increment = false)]
        pub tenant_id: String,
        #[sea_orm(primary_key, auto_increment = false)]
        pub attachment_id: String,
        pub application_id: String,
        pub application_version: i32,
        pub purpose: String,
        pub object_key_ciphertext: String,
        pub filename_ciphertext: String,
        pub media_type: String,
        pub size_bytes: i64,
        pub content_sha256: String,
        pub malware_scan_status: String,
        pub malware_scan_provider: Option<String>,
        pub malware_scan_completed_at: Option<DateTimeWithTimeZone>,
        pub created_at: DateTimeWithTimeZone,
    }

    #[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
    pub enum Relation {}

    impl ActiveModelBehavior for ActiveModel {}
}

pub mod support_plans {
    use sea_orm::entity::prelude::*;

    #[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
    #[sea_orm(table_name = "support_plans", schema_name = "fiducia_commercial")]
    pub struct Model {
        #[sea_orm(primary_key, auto_increment = false)]
        pub tenant_id: String,
        #[sea_orm(primary_key, auto_increment = false)]
        pub support_plan_id: String,
        pub current_version: i32,
        pub current_status: String,
        pub created_at: DateTimeWithTimeZone,
        pub updated_at: DateTimeWithTimeZone,
    }

    #[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
    pub enum Relation {}

    impl ActiveModelBehavior for ActiveModel {}
}

pub mod support_plan_versions {
    use sea_orm::entity::prelude::*;

    #[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
    #[sea_orm(table_name = "support_plan_versions", schema_name = "fiducia_commercial")]
    pub struct Model {
        #[sea_orm(primary_key, auto_increment = false)]
        pub tenant_id: String,
        #[sea_orm(primary_key, auto_increment = false)]
        pub support_plan_id: String,
        #[sea_orm(primary_key, auto_increment = false)]
        pub version: i32,
        pub status: String,
        pub name: String,
        pub tier: String,
        pub coverage: String,
        pub policy_document: Json,
        pub content_sha256: String,
        pub supersedes_version: Option<i32>,
        pub approved_by_subject_hash: Option<String>,
        pub approved_at: Option<DateTimeWithTimeZone>,
        pub created_at: DateTimeWithTimeZone,
    }

    #[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
    pub enum Relation {}

    impl ActiveModelBehavior for ActiveModel {}
}

pub mod sla_policies {
    use sea_orm::entity::prelude::*;

    #[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
    #[sea_orm(table_name = "sla_policies", schema_name = "fiducia_commercial")]
    pub struct Model {
        #[sea_orm(primary_key, auto_increment = false)]
        pub tenant_id: String,
        #[sea_orm(primary_key, auto_increment = false)]
        pub sla_policy_id: String,
        pub current_version: i32,
        pub current_status: String,
        pub created_at: DateTimeWithTimeZone,
        pub updated_at: DateTimeWithTimeZone,
    }

    #[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
    pub enum Relation {}

    impl ActiveModelBehavior for ActiveModel {}
}

pub mod sla_policy_versions {
    use sea_orm::entity::prelude::*;

    #[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
    #[sea_orm(table_name = "sla_policy_versions", schema_name = "fiducia_commercial")]
    pub struct Model {
        #[sea_orm(primary_key, auto_increment = false)]
        pub tenant_id: String,
        #[sea_orm(primary_key, auto_increment = false)]
        pub sla_policy_id: String,
        #[sea_orm(primary_key, auto_increment = false)]
        pub version: i32,
        pub status: String,
        pub name: String,
        pub availability_target_bps: i32,
        pub measurement_window: String,
        pub policy_document: Json,
        pub content_sha256: String,
        pub supersedes_version: Option<i32>,
        pub approved_by_subject_hash: Option<String>,
        pub approved_at: Option<DateTimeWithTimeZone>,
        pub created_at: DateTimeWithTimeZone,
    }

    #[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
    pub enum Relation {}

    impl ActiveModelBehavior for ActiveModel {}
}

pub mod contract_templates {
    use sea_orm::entity::prelude::*;

    #[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
    #[sea_orm(table_name = "contract_templates", schema_name = "fiducia_commercial")]
    pub struct Model {
        #[sea_orm(primary_key, auto_increment = false)]
        pub tenant_id: String,
        #[sea_orm(primary_key, auto_increment = false)]
        pub contract_template_id: String,
        pub kind: String,
        pub current_version: i32,
        pub current_status: String,
        pub created_at: DateTimeWithTimeZone,
        pub updated_at: DateTimeWithTimeZone,
    }

    #[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
    pub enum Relation {}

    impl ActiveModelBehavior for ActiveModel {}
}
