"""Render deterministic SeaORM and Diesel projections."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from model_contract import (
    DIESEL_MODELS_PATH,
    DIESEL_RUST_TYPES,
    DIESEL_SCHEMA_PATH,
    DIESEL_SQL_TYPES,
    SEAORM_MOD_PATH,
    SEAORM_PART_PATHS,
    SEA_TYPES,
    ContractError,
    _optional,
)

# These stable cutoffs mirror rustfmt 1.88 for the exact attribute forms emitted
# below. Exact-head CI runs rustfmt after regeneration to keep this invariant
# visible if the pinned formatter or generated syntax changes.
SEAORM_ATTRIBUTE_INLINE_WIDTH = 86
DIESEL_ATTRIBUTE_INLINE_WIDTH = 80


def render_seaorm_part(tables: list[dict[str, Any]]) -> str:
    output = [
        "// @generated by quote-system/rust/scripts/model_codegen.py; do not edit by hand.\n",
        "#![allow(clippy::module_name_repetitions)]\n",
        "\n",
        "// SeaORM entities projected from `db/0001_commercial_intake.sql`.\n",
        "//\n",
        "// Public API payloads remain owned by TypeSpec and JSON Schema. These models\n",
        "// intentionally represent encrypted persistence rows only.\n",
    ]
    for table in tables:
        output.append(f"\npub mod {table['table']} {{\n")
        output.append("    use sea_orm::entity::prelude::*;\n\n")
        output.append(
            "    #[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]\n"
        )
        sea_orm_attribute = (
            f'    #[sea_orm(table_name = "{table["table"]}", '
            'schema_name = "fiducia_commercial")]'
        )
        if len(sea_orm_attribute) <= SEAORM_ATTRIBUTE_INLINE_WIDTH:
            output.append(f"{sea_orm_attribute}\n")
        else:
            output.extend(
                [
                    "    #[sea_orm(\n",
                    f'        table_name = "{table["table"]}",\n',
                    '        schema_name = "fiducia_commercial"\n',
                    "    )]\n",
                ]
            )
        output.append("    pub struct Model {\n")
        primary_key = set(table["primary_key"])
        for column in table["columns"]:
            if column["name"] in primary_key:
                output.append(
                    "        #[sea_orm(primary_key, auto_increment = false)]\n"
                )
            output.append(
                f"        pub {column['name']}: "
                f"{_optional(SEA_TYPES[column['sql_type']], column['nullable'])},\n"
            )
        output.append("    }\n\n")
        output.append(
            "    #[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]\n"
        )
        output.append("    pub enum Relation {}\n\n")
        output.append("    impl ActiveModelBehavior for ActiveModel {}\n")
        output.append("}\n")
    return "".join(output)


def split_seaorm_tables(
    tables: list[dict[str, Any]],
) -> list[list[dict[str, Any]]]:
    chunk_sizes = (6, 6, 5, 5)
    if sum(chunk_sizes) != len(tables):
        raise ContractError(
            f"SeaORM projection expects 22 tables, found {len(tables)}"
        )
    chunks = []
    offset = 0
    for size in chunk_sizes:
        chunks.append(tables[offset : offset + size])
        offset += size
    return chunks


def render_seaorm_mod() -> str:
    output = [
        "// @generated by quote-system/rust/scripts/model_codegen.py; do not edit by hand.\n",
        "\n",
    ]
    for index in range(1, 5):
        output.append(f"mod part_{index:02d};\n")
    output.append("\n")
    for index in range(1, 5):
        output.append(f"pub use part_{index:02d}::*;\n")
    return "".join(output)


def render_diesel_schema(tables: list[dict[str, Any]]) -> str:
    output = [
        "// @generated by quote-system/rust/scripts/model_codegen.py; do not edit by hand.\n",
        "\n",
    ]
    for table in tables:
        primary_key = ", ".join(table["primary_key"])
        output.append("diesel::table! {\n")
        output.append(
            f"    fiducia_commercial.{table['table']} ({primary_key}) {{\n"
        )
        for column in table["columns"]:
            sql_type = DIESEL_SQL_TYPES[column["sql_type"]]
            if column["nullable"]:
                sql_type = f"Nullable<{sql_type}>"
            output.append(f"        {column['name']} -> {sql_type},\n")
        output.append("    }\n")
        output.append("}\n\n")
    return "".join(output).rstrip() + "\n"


def render_diesel_models(tables: list[dict[str, Any]]) -> str:
    output = [
        "// @generated by quote-system/rust/scripts/model_codegen.py; do not edit by hand.\n",
        "\n",
        "use bigdecimal::BigDecimal;\n",
        "use chrono::{DateTime, Utc};\n",
        "use diesel::prelude::*;\n",
        "use serde_json::Value;\n",
        "\n",
        "use crate::schema;\n",
    ]
    for table in tables:
        primary_key = ", ".join(table["primary_key"])
        output.append("\n")
        output.append(
            "#[derive(Clone, Debug, PartialEq, Eq, Queryable, Selectable, Identifiable)]\n"
        )
        output.append(
            f"#[diesel(table_name = schema::{table['table']})]\n"
        )
        primary_key_attribute = f"#[diesel(primary_key({primary_key}))]"
        if len(primary_key_attribute) <= DIESEL_ATTRIBUTE_INLINE_WIDTH:
            output.append(f"{primary_key_attribute}\n")
        else:
            output.append("#[diesel(primary_key(\n")
            for primary_key_column in table["primary_key"]:
                output.append(f"    {primary_key_column},\n")
            output.append("))]\n")
        output.append(f"pub struct {table['model_name']}Row {{\n")
        for column in table["columns"]:
            rust_type = _optional(
                DIESEL_RUST_TYPES[column["sql_type"]], column["nullable"]
            )
            output.append(f"    pub {column['name']}: {rust_type},\n")
        output.append("}\n")
    return "".join(output)


def generated_outputs(manifest: dict[str, Any]) -> dict[Path, str]:
    tables = manifest["tables"]
    outputs = {
        SEAORM_MOD_PATH: render_seaorm_mod(),
        DIESEL_SCHEMA_PATH: render_diesel_schema(tables),
        DIESEL_MODELS_PATH: render_diesel_models(tables),
    }
    for path, chunk in zip(SEAORM_PART_PATHS, split_seaorm_tables(tables)):
        outputs[path] = render_seaorm_part(chunk)
    return outputs
