apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - networkpolicy.yaml
patches:
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: fiducia-nats
      namespace: fiducia
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/ports/-
        value:
          containerPort: 6222
          name: route
          protocol: TCP
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value:
          name: route-tls
          mountPath: /etc/nats/route-tls
          readOnly: true
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: route-tls
          secret:
            secretName: fiducia-nats-route-tls
            optional: false
            defaultMode: 0440
