apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fiducia
resources:
  - ../../common
configMapGenerator:
  - name: fiducia-cluster
    envs: [topology.env]
generatorOptions:
  disableNameSuffixHash: true
patches:
  - path: patches.yaml
