#!/usr/bin/env node
// Fan topology.toml out into per-cluster kustomize inputs + the edge region list.
//
//   node tools/render.mjs          # write generated inputs
//   node tools/render.mjs --check  # CI: fail if any generated file is stale
//
// topology.toml is the single source of truth. Generated, checked-in outputs:
//   clusters/<name>/topology.env   <- configMapGenerator envs (cluster id, peers)
//   clusters/<name>/patches.yaml   <- storage class + node replicas
//   generated/edge-regions.json    <- FIDUCIA_REGIONS for fiducia-edge

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, "..");
const BANNER = "GENERATED by tools/render.mjs from topology.toml — do not edit.";

class RenderError extends Error {}
const fail = (m) => { throw new RenderError(m); };

// --- minimal TOML reader (the constrained subset topology.toml uses) ---------
// Supports: `key = "str" | int | true | false`, [table], and [[array.of.tables]].
// Comments and blanks on their own lines only.
export function parseToml(text) {
  const rootObj = {};
  const arrays = {};
  let cur = rootObj;
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;
    let m;
    if ((m = line.match(/^\[\[(\w+)\]\]$/))) {
      const k = m[1];
      (arrays[k] ||= []).push((cur = {}));
    } else if ((m = line.match(/^\[(\w+)\]$/))) {
      cur = rootObj[m[1]] ||= {};
    } else if ((m = line.match(/^([A-Za-z0-9_]+)\s*=\s*(.+)$/))) {
      cur[m[1]] = parseVal(m[2].trim(), raw);
    } else {
      fail(`cannot parse TOML line: ${raw}`);
    }
  }
  return { ...rootObj, ...arrays };
}
function parseVal(v, raw) {
  if (/^".*"$/.test(v)) return v.slice(1, -1);
  if (/^-?\d+$/.test(v)) return parseInt(v, 10);
  if (v === "true") return true;
  if (v === "false") return false;
  fail(`unsupported TOML value (use "string", int, or bool): ${raw}`);
}

// --- load + validate ---------------------------------------------------------

export function loadTopology() {
  const file = path.join(root, "topology.toml");
  if (!fs.existsSync(file)) fail("missing topology.toml");
  const t = parseToml(fs.readFileSync(file, "utf8"));
  for (const k of ["cluster_id", "shard_count", "replication_factor", "connectivity"]) {
    if (t[k] === undefined) fail(`topology.toml missing top-level ${k}`);
  }
  const clusters = t.cluster || [];
  if (!Array.isArray(clusters) || clusters.length === 0) fail("topology.toml has no [[cluster]] blocks");
  if (clusters.length < t.replication_factor) {
    fail(`need at least replication_factor (${t.replication_factor}) clusters for quorum; have ${clusters.length}`);
  }
  const seen = new Set();
  const required = ["name", "storage_class", "node_replicas", "brain_endpoint", "node_peer_endpoint", "lb_endpoint"];
  for (const c of clusters) {
    for (const k of required) if (c[k] === undefined) fail(`cluster ${c.name || "?"} missing ${k}`);
    if (seen.has(c.name)) fail(`duplicate cluster name: ${c.name}`);
    seen.add(c.name);
  }
  if (!["clustermesh", "wireguard", "public-mtls"].includes(t.connectivity)) {
    fail(`connectivity must be clustermesh|wireguard|public-mtls, got ${t.connectivity}`);
  }
  // Raft timing is optional; default to WAN-safe values (the node's own built-in
  // defaults are LAN values that would flap across clouds). If present, sanity-
  // check that the election timeout sits comfortably above the heartbeat — the
  // same invariant RaftTiming::from_env warns about at runtime.
  const raft = { tick_ms: 50, heartbeat_ms: 150, election_min_ms: 1000, election_jitter_ms: 1000, check_quorum: true, ...(t.raft || {}) };
  for (const k of ["tick_ms", "heartbeat_ms", "election_min_ms", "election_jitter_ms"]) {
    if (!Number.isInteger(raft[k]) || raft[k] <= 0) fail(`[raft].${k} must be a positive integer`);
  }
  if (typeof raft.check_quorum !== "boolean") fail(`[raft].check_quorum must be a boolean`);
  if (raft.election_min_ms < raft.heartbeat_ms * 3) {
    fail(`[raft].election_min_ms (${raft.election_min_ms}) must be >= 3x heartbeat_ms (${raft.heartbeat_ms}) to avoid spurious elections`);
  }
  t.raft = raft;
  return t;
}

// --- render ------------------------------------------------------------------

export function render(t) {
  const clusters = t.cluster;
  const targetNodes = clusters.reduce((n, c) => n + c.node_replicas, 0);
  const files = {};

  for (const c of clusters) {
    const others = clusters.filter((o) => o.name !== c.name);
    const peers = others.map((o) => o.node_peer_endpoint).join(",");
    const brainPeers = others.map((o) => o.brain_endpoint).join(",");

    files[`clusters/${c.name}/topology.env`] = [
      `# ${BANNER}`,
      `FIDUCIA_CLUSTER=${c.name}`,
      `FIDUCIA_CLUSTER_ID=${t.cluster_id}`,
      `FIDUCIA_SHARD_COUNT=${t.shard_count}`,
      `FIDUCIA_REPLICATION_FACTOR=${t.replication_factor}`,
      `FIDUCIA_TARGET_NODES=${targetNodes}`,
      `FIDUCIA_PEERS=${peers}`,
      `FIDUCIA_BRAIN_PEERS=${brainPeers}`,
      // Cross-cloud Raft timing (read by RaftTiming::from_env in fiducia-node).
      `FIDUCIA_RAFT_TICK_MS=${t.raft.tick_ms}`,
      `FIDUCIA_RAFT_HEARTBEAT_MS=${t.raft.heartbeat_ms}`,
      `FIDUCIA_RAFT_ELECTION_MIN_MS=${t.raft.election_min_ms}`,
      `FIDUCIA_RAFT_ELECTION_JITTER_MS=${t.raft.election_jitter_ms}`,
      "",
    ].join("\n");

    files[`clusters/${c.name}/patches.yaml`] = `# ${BANNER}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fiducia-node
  namespace: fiducia
spec:
  replicas: ${c.node_replicas}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: ${c.storage_class}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fiducia-brain
  namespace: fiducia
spec:
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: ${c.storage_class}
`;
  }

  // Edge region list (fiducia-edge FIDUCIA_REGIONS).
  files["generated/edge-regions.json"] =
    JSON.stringify(clusters.map((c) => ({ name: c.name, url: c.lb_endpoint })), null, 2) + "\n";

  return files;
}

// --- run ---------------------------------------------------------------------

function main() {
  const check = process.argv.includes("--check");
  let files;
  try {
    files = render(loadTopology());
  } catch (e) {
    if (e instanceof RenderError) { console.error(`error: ${e.message}`); process.exit(2); }
    throw e;
  }
  let drift = 0;
  for (const [rel, content] of Object.entries(files)) {
    const abs = path.join(root, rel);
    if (check) {
      const cur = fs.existsSync(abs) ? fs.readFileSync(abs, "utf8") : null;
      if (cur !== content) { console.error(`drift: ${rel}`); drift++; }
    } else {
      fs.mkdirSync(path.dirname(abs), { recursive: true });
      fs.writeFileSync(abs, content);
      console.log(`wrote ${rel}`);
    }
  }
  if (check && drift) { console.error(`${drift} file(s) stale — run: node tools/render.mjs`); process.exit(1); }
  if (check) console.log("topology in sync");
}

const isMain = process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href;
if (isMain) main();
