#!/usr/bin/env node
// Fan topology.toml out into per-cluster kustomize inputs + the edge region list.
//
//   node tools/render.mjs          # write generated inputs
//   node tools/render.mjs --check  # CI: fail if any generated file is stale
//
// topology.toml is the single source of truth. Generated, checked-in outputs:
//   clusters/<name>/topology.env   <- configMapGenerator envs (cluster id, peers)
//   clusters/<name>/patches.yaml   <- storage class + node replicas
//   generated/edge-regions.json    <- FIDUCIA_REGIONS for fiducia-edge

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, "..");
const bannerFor = (sourceName) => `GENERATED by tools/render.mjs from ${sourceName} — do not edit.`;

class RenderError extends Error {}
const fail = (m) => { throw new RenderError(m); };

// A cluster name becomes an output DIRECTORY (clusters/<name>/…) and a k8s
// label, so it must be a DNS-1123 label: lowercase alphanumeric + hyphens,
// max 63 chars. Checked in validateTopology AND re-checked in render() —
// render() is exported, so a caller skipping validation must still be unable
// to write outside clusters/.
const NAME_RE = /^[a-z0-9]([a-z0-9-]*[a-z0-9])?$/;
const safeName = (n) => typeof n === "string" && n.length <= 63 && NAME_RE.test(n);

// --- minimal TOML reader (the constrained subset topology.toml uses) ---------
// Supports: `key = "str" | int | true | false`, [table], and [[array.of.tables]].
// Comments and blanks on their own lines only.
export function parseToml(text) {
  // Null-prototype tables: a hostile key can only ever land on the data object,
  // never on Object.prototype.
  const rootObj = Object.create(null);
  const arrays = Object.create(null);
  let cur = rootObj;
  // Keys that target the prototype chain (or the constructor) are prototype
  // pollution regardless of the receiver — reject outright.
  const FORBIDDEN_KEYS = new Set(["__proto__", "constructor", "prototype"]);
  const checkKey = (k, raw) => {
    if (FORBIDDEN_KEYS.has(k)) fail(`forbidden key name: ${raw}`);
    return k;
  };
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;
    let m;
    if ((m = line.match(/^\[\[(\w+)\]\]$/))) {
      const k = checkKey(m[1], raw);
      (arrays[k] ||= []).push((cur = Object.create(null)));
    } else if ((m = line.match(/^\[(\w+)\]$/))) {
      cur = rootObj[checkKey(m[1], raw)] ||= Object.create(null);
    } else if ((m = line.match(/^([A-Za-z0-9_]+)\s*=\s*(.+)$/))) {
      cur[checkKey(m[1], raw)] = parseVal(m[2].trim(), raw);
    } else {
      fail(`cannot parse TOML line: ${raw}`);
    }
  }
  return Object.assign(Object.create(null), rootObj, arrays);
}
function parseVal(v, raw) {
  if (/^".*"$/.test(v)) return v.slice(1, -1);
  if (/^-?\d+$/.test(v)) return parseInt(v, 10);
  if (v === "true") return true;
  if (v === "false") return false;
  fail(`unsupported TOML value (use "string", int, or bool): ${raw}`);
}

// --- load + validate ---------------------------------------------------------

export function loadTopology(file = path.join(root, "topology.toml")) {
  if (!fs.existsSync(file)) fail(`missing topology file: ${file}`);
  return validateTopology(parseToml(fs.readFileSync(file, "utf8")));
}

export function validateTopology(t) {
  for (const k of ["cluster_id", "shard_count", "replication_factor", "connectivity"]) {
    if (t[k] === undefined) fail(`topology.toml missing top-level ${k}`);
  }
  // Bounds: these are string-typed if the TOML author quoted them, which would make
  // the quorum guards below compare/sum via JS coercion (a string RF silently
  // passes `clusters.length < "3"`; a string node_replicas string-concatenates into
  // FIDUCIA_TARGET_NODES). Require real positive integers. Upper bounds are typo
  // rails, not tuning: shard_count past 2^16 or RF past 7 is never a real deployment.
  const TOP_BOUNDS = { shard_count: 65536, replication_factor: 7 };
  for (const [k, max] of Object.entries(TOP_BOUNDS)) {
    if (!Number.isInteger(t[k]) || t[k] < 1 || t[k] > max) {
      fail(`topology.toml ${k} must be a positive integer <= ${max}, got ${JSON.stringify(t[k])}`);
    }
  }
  const clusters = t.cluster || [];
  if (!Array.isArray(clusters) || clusters.length === 0) fail("topology.toml has no [[cluster]] blocks");
  if (clusters.length < t.replication_factor) {
    fail(`need at least replication_factor (${t.replication_factor}) clusters for quorum; have ${clusters.length}`);
  }
  const seen = new Set();
  const required = ["name", "storage_class", "node_replicas", "brain_endpoint", "node_peer_endpoint", "lb_endpoint"];
  // Without the name check, `name = "../../etc/x"` escapes the repo on `render`
  // (arbitrary file write) / reads an arbitrary path on --check. See safeName.
  // Peer endpoints are dialed as host:port (mesh DNS or IP); lb_endpoint is a URL.
  const HOSTPORT_RE = /^[a-z0-9]([a-z0-9.-]*[a-z0-9])?:(\d{1,5})$/i;
  for (const c of clusters) {
    for (const k of required) if (c[k] === undefined) fail(`cluster ${c.name || "?"} missing ${k}`);
    if (!safeName(c.name)) {
      fail(`cluster name ${JSON.stringify(c.name)} must be DNS-1123 (lowercase alphanumeric + hyphens, <= 63 chars) — it becomes a directory + k8s label`);
    }
    if (!Number.isInteger(c.node_replicas) || c.node_replicas < 1 || c.node_replicas > 1000) {
      fail(`cluster ${c.name} node_replicas must be a positive integer <= 1000, got ${JSON.stringify(c.node_replicas)}`);
    }
    for (const ep of ["brain_endpoint", "node_peer_endpoint", ...(c.node_api_endpoint === undefined ? [] : ["node_api_endpoint"])]) {
      const hp = HOSTPORT_RE.exec(String(c[ep]));
      if (!hp) fail(`cluster ${c.name} ${ep} must be host:port, got ${JSON.stringify(c[ep])}`);
      const port = parseInt(hp[2], 10);
      if (port < 1 || port > 65535) fail(`cluster ${c.name} ${ep} port must be in 1..65535, got ${port}`);
    }
    if (!/^https?:\/\/[^\s]+$/.test(String(c.lb_endpoint))) {
      fail(`cluster ${c.name} lb_endpoint must be an http(s) URL, got ${JSON.stringify(c.lb_endpoint)}`);
    }
    if (seen.has(c.name)) fail(`duplicate cluster name: ${c.name}`);
    seen.add(c.name);
  }
  // Brain membership: a cluster runs a brain member unless `brain = false`
  // (node-only). The brain Raft group must be an ODD number >= replication_factor
  // for clean quorum — an even group (e.g. 4) has the same fault tolerance as the
  // odd one below it but worse quorum math. So a 4th cluster is added node-only.
  for (const c of clusters) {
    if (c.brain === undefined) c.brain = true;
    if (typeof c.brain !== "boolean") fail(`cluster ${c.name} brain must be a boolean`);
  }
  const brainCount = clusters.filter((c) => c.brain).length;
  if (brainCount < t.replication_factor) {
    fail(`brain group (${brainCount}) must be >= replication_factor (${t.replication_factor})`);
  }
  if (brainCount % 2 === 0) {
    fail(`brain group must be an ODD number of members for clean quorum; got ${brainCount} — mark a cluster brain = false`);
  }
  if (!["clustermesh", "wireguard", "public-mtls", "private-network"].includes(t.connectivity)) {
    fail(`connectivity must be clustermesh|wireguard|public-mtls|private-network, got ${t.connectivity}`);
  }
  // Raft timing is optional; default to WAN-safe values (the node's own built-in
  // defaults are LAN values that would flap across clouds). If present, sanity-
  // check that the election timeout sits comfortably above the heartbeat — the
  // same invariant RaftTiming::from_env warns about at runtime.
  const raft = { tick_ms: 50, heartbeat_ms: 150, election_min_ms: 1000, election_jitter_ms: 1000, check_quorum: true, ...(t.raft || {}) };
  for (const k of ["tick_ms", "heartbeat_ms", "election_min_ms", "election_jitter_ms"]) {
    if (!Number.isInteger(raft[k]) || raft[k] <= 0) fail(`[raft].${k} must be a positive integer`);
  }
  if (typeof raft.check_quorum !== "boolean") fail(`[raft].check_quorum must be a boolean`);
  if (raft.election_min_ms < raft.heartbeat_ms * 3) {
    fail(`[raft].election_min_ms (${raft.election_min_ms}) must be >= 3x heartbeat_ms (${raft.heartbeat_ms}) to avoid spurious elections`);
  }
  t.raft = raft;
  if (t.auth_required !== undefined && typeof t.auth_required !== "boolean") {
    fail("auth_required must be a boolean when present");
  }
  return t;
}

// --- render ------------------------------------------------------------------

export function render(t, {
  clusterRoot = "clusters",
  edgeOutput = "generated/edge-regions.json",
  sourceName = "topology.toml",
} = {}) {
  const clusters = t.cluster;
  const targetNodes = clusters.reduce((n, c) => n + c.node_replicas, 0);
  const files = {};
  const banner = bannerFor(sourceName);

  const brainClusters = clusters.filter((o) => o.brain);
  for (const c of clusters) {
    // c.name becomes a path component below; re-assert even for callers that
    // bypassed validateTopology.
    if (!safeName(c.name)) fail(`unsafe cluster name for output path: ${JSON.stringify(c.name)}`);
    const others = clusters.filter((o) => o.name !== c.name);
    const peers = others.map((o) => o.node_peer_endpoint).join(",");
    // Brain members list their OTHER brain peers (their Raft peer set); node-only
    // clusters list ALL brains (their sidecars reach the control plane but they
    // are not members of the brain Raft group).
    const brainPeers = (c.brain ? brainClusters.filter((o) => o.name !== c.name) : brainClusters)
      .map((o) => o.brain_endpoint)
      .join(",");

    files[`${clusterRoot}/${c.name}/topology.env`] = [
      `# ${banner}`,
      `FIDUCIA_CLUSTER=${c.name}`,
      `FIDUCIA_CLUSTER_ID=${t.cluster_id}`,
      `FIDUCIA_SHARD_COUNT=${t.shard_count}`,
      `FIDUCIA_REPLICATION_FACTOR=${t.replication_factor}`,
      `FIDUCIA_TARGET_NODES=${targetNodes}`,
      ...(c.node_api_endpoint === undefined ? [] : [`FIDUCIA_SELF_ADDR=${c.node_api_endpoint}`]),
      `FIDUCIA_PEERS=${peers}`,
      `FIDUCIA_BRAIN_PEERS=${brainPeers}`,
      // Cross-cloud Raft timing (read by RaftTiming::from_env in fiducia-node).
      `FIDUCIA_RAFT_TICK_MS=${t.raft.tick_ms}`,
      `FIDUCIA_RAFT_HEARTBEAT_MS=${t.raft.heartbeat_ms}`,
      `FIDUCIA_RAFT_ELECTION_MIN_MS=${t.raft.election_min_ms}`,
      `FIDUCIA_RAFT_ELECTION_JITTER_MS=${t.raft.election_jitter_ms}`,
      // CheckQuorum / leader lease: a partitioned leader steps down and refuses
      // stale linearizable reads instead of answering authoritatively. On by
      // default; only set to off to debug a leadership/liveness issue.
      `FIDUCIA_RAFT_CHECK_QUORUM=${t.raft.check_quorum ? "on" : "off"}`,
      ...(t.auth_required === undefined ? [] : [`FIDUCIA_AUTH_REQUIRED=${t.auth_required ? "true" : "false"}`]),
      "",
    ].join("\n");

    // Node StatefulSet patch (replicas + storage class) applies to every cluster.
    //
    // IMPORTANT: volumeClaimTemplates has NO strategic-merge key, so kustomize
    // REPLACES the whole list — a patch carrying only storageClassName silently
    // drops accessModes/resources and the API server then rejects the
    // StatefulSet ("at least 1 access mode is required"). Every patch must
    // restate the FULL PVC spec. Sizes mirror base/ (node 10Gi, brain 2Gi).
    const pvc = (storageClass, size) => `  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: ${size}
        storageClassName: ${storageClass}`;

    const patches = [`apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fiducia-node
  namespace: fiducia
spec:
  replicas: ${c.node_replicas}
${pvc(c.storage_class, "10Gi")}`];

    // Voluntary-disruption guard, sized to THIS cluster's node count.
    // base/node/pdb.yaml carries maxUnavailable: 1, which is correct only for the
    // >= 3-replica shape base assumes. With one or two nodes per cluster — and a
    // shard's 3 replicas spread ONE PER CLUSTER — maxUnavailable: 1 permits
    // evicting 100% of this cluster's Raft member, and each cluster's PDB is
    // blind to the other two, so two concurrent drains take every shard below
    // write quorum. Block voluntary eviction outright instead: a drain must be
    // consciously overridden by an operator who has checked the other clusters
    // (identical reasoning to base/components/brain/pdb.yaml).
    if (c.node_replicas <= 2) {
      patches.push(`apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: fiducia-node
  namespace: fiducia
spec:
  maxUnavailable: 0`);
    }

    // Brain storage patch only on brain clusters. Whether a cluster RUNS a brain
    // is decided by its overlay including the `base/components/brain` Component
    // (hand-authored in clusters/<name>/kustomization.yaml); node-only clusters
    // omit both the Component and this patch, so they never join the brain group.
    if (c.brain) {
      // FIDUCIA_BRAIN_ID doubles as the address the OTHER brains dial: it is the
      // leader_id gossiped in brain-Raft, and a follower forwards /v1 reads and
      // writes to `{leader_id}/forward/v1/...` on the peer plane. The base sets a
      // display-style id (`$(POD_NAME).$(FIDUCIA_CLUSTER)`) which resolves
      // nowhere, so every follower forward blackholes: /v1/nodes 502s on the two
      // followers, each LB then fails to refresh its brain node snapshot and
      // serves 502 on the data path, and the leader only ever learns about nodes
      // whose sidecars heartbeat it directly (nodes=1, every shard reported
      // under-replicated). Advertise this member's dialable peer-plane URL —
      // the same `brain_endpoint` the other clusters already list in
      // FIDUCIA_BRAIN_PEERS. Container env strategic-merges on `name`, so this
      // replaces the base entry rather than appending a duplicate.
      patches.push(`apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fiducia-brain
  namespace: fiducia
spec:
  template:
    spec:
      containers:
        - name: brain
          env:
            - name: FIDUCIA_BRAIN_ID
              value: "http://${c.brain_endpoint}"
${pvc(c.storage_class, "2Gi")}`);
    }

    files[`${clusterRoot}/${c.name}/patches.yaml`] = `# ${banner}\n${patches.join("\n---\n")}\n`;
  }

  // Edge region list (fiducia-edge FIDUCIA_REGIONS).
  files[edgeOutput] =
    JSON.stringify(clusters.map((c) => ({ name: c.name, url: c.lb_endpoint })), null, 2) + "\n";

  return files;
}

// --- run ---------------------------------------------------------------------

function main() {
  const check = process.argv.includes("--check") || /^(1|true|yes|on)$/i.test(process.env.FIDUCIA_RENDER_CHECK ?? "");
  let files;
  try {
    files = render(loadTopology());
  } catch (e) {
    if (e instanceof RenderError) { console.error(`error: ${e.message}`); process.exit(2); }
    throw e;
  }
  let drift = 0;
  for (const [rel, content] of Object.entries(files)) {
    const abs = path.join(root, rel);
    if (check) {
      const cur = fs.existsSync(abs) ? fs.readFileSync(abs, "utf8") : null;
      if (cur !== content) { console.error(`drift: ${rel}`); drift++; }
    } else {
      fs.mkdirSync(path.dirname(abs), { recursive: true });
      fs.writeFileSync(abs, content);
      console.log(`wrote ${rel}`);
    }
  }
  if (check && drift) { console.error(`${drift} file(s) stale — run: node tools/render.mjs`); process.exit(1); }
  if (check) console.log("topology in sync");
}

const isMain = process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href;
if (isMain) main();
