name: proof ORES comparisons runtime all 18

on:
  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/proof-ores-comparisons-runtime-18.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  runtime-18:
    uses: ORESoftware/ores-comparisons/.github/workflows/runtime-all-18.yml@02c353bfc8fb335f82bf85353254c7dae270555e
    secrets:
      COMPARISON_REPO_READ_TOKEN: ${{ secrets.ORE_SOURCE_PAT }}
