name: proof ORES comparisons runtime all 18

on:
  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/proof-ores-comparisons-runtime-18.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  runtime-18:
    uses: ORESoftware/ores-comparisons/.github/workflows/runtime-all-18.yml@92ba4ab50a16524262542fd57d48cd0d932b203e
    secrets:
      COMPARISON_REPO_READ_TOKEN: ${{ secrets.ORE_SOURCE_PAT }}
